### PR TITLE
Remove query from file name 

### PR DESCRIPTION
**Pull request by quthla**
This removes query from the file name and only takes the actual path for basename

### CODE REVIEW

**Comment by romanvm** [comment]
What is the purpose of this change?

**Comment by quthla** [comment]
It's already a few months since I applied this fix but iirc the addon would always fail to extract episode data from http URLs with query like http://hostname/dir/file?query

**Comment by romanvm** [comment]
Have you tested this with local paths and paths from network filesystems, like `smb://foo/bar/baz.mp4`?

**Comment by quthla** [comment]
It'll parse any url no matter the scheme and even if there are parts missing. See examples here https://docs.python.org/3/library/urllib.parse.html

**Comment by quthla** [comment]
> parse.urlparse("smb://foo/bar/baz.mp4")
ParseResult(scheme='smb', netloc='foo', path='/bar/baz.mp4', params='', query='', fragment='')

**Comment by romanvm** [comment]
Thank your for the explanation. I'll check it myself.

**Comment by romanvm** [comment]
Unfortunately I had no time to test it properly but let's assume it works. Thank you for your contribution.

**Pull request merged**
